version: '3.3'

services:
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'study'
      MYSQL_USER: 'mysql'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'

    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./my-db:/var/lib/mysql
